### ISSUE TITLE
Formatting negative numbers causes IE11 to crash

### ISSUE THREAD

**Issue by nonmetalhail** [MeTaNoV/numbro-element#1]
Apparently, trying to assign a `'-'` with `.textContent`  on a `span` causes IE11 to totally crash. Of course, this only happens when the dev tools are not open. 

One solution (as suggested here https://connect.microsoft.com/IE/feedback/details/851144/assigning-textcontent-crashes-the-browser-tab ) is to use `.innerText` instead, but that could have some performance impacts. Perhaps bindings might be another approach.

**Comment by GeoloeG-IsT** [comment]
ThX for the report, I used temporally `.innerText` but will probably switch to a data binding implementation once I'll do the migration to 2.0
Note. Interesting that GE forked this component w/o even telling it... Let's say, it is an honor! ;)

**Comment by aaronbeall** [comment]
> Apparently, trying to assign a '-' with .textContent on a span causes IE11 to totally crash. Of course, this only happens when the dev tools are not open.

This is the kind of sentence that sounds like it should be a misunderstanding. But it's not. It's exactly true. After nearly 2 full days of tracking down why IE11 was randomly crashing it came down to `.textContent = "-"` *only when the dev tools aren't open.* Googling to re-assure myself of sanity brought me here.
